apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsiplugin-pv
  labels:
    name: data-iscsiplugin
spec:
  storageClassName: csi-iscsi
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ISCSI
    volumeHandle: iscsi-data-id
    volumeAttributes: 
      targetPortal: "192.168.122.145:3260"
      portals: "[]"
      iqn: "iqn.2003-01.org.linux-iscsi.example:targetd"
      lun: "0"
      iscsiInterface: "default"
      discoveryCHAPAuth: "false"
      sessionCHAPAuth: "false"
